server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: bank_user
    password: bank_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          secret-key: mySecretKeyForJWTGenerationWhichIsVeryLongAndSecure123!

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method


logging:
  level:
    com.bank: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
    secret: mySecretKeyForJWTGenerationWhichIsVeryLongAndSecure123!
    expiration: 86400000 # 24 hours